# Generated by Django 4.2.13 on 2024-06-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Cliente',
        ),
    ]
