# Generated by Django 4.2.13 on 2024-06-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_usuario_rename_alumno_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
